version: '3.9'

services:
  web:
    image: tracking-webservice:${BUILD_NUMBER}
    networks:
      - traefik-public
    ports:
      - 8180:8080
    volumes:
      - /mnt/shared/docker/tracking-webservice:/tracking-webservice
    configs:
      - source: okta_ws_tomcat-users.xml
        target: /usr/local/tomcat/conf/tomcat-users.xml
      - source: tracking-webservice.properties
        target: /usr/src/tracking-webservice.properties
    healthcheck:
      test: curl --fail http://localhost:8080/health-check || exit 1
      start_period: 10s
      interval: 10s
      retries: 3
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
      update_config:
        order: start-first
        failure_action: rollback
        parallelism: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.tracking-webservice-http.rule=Host(`tracking-api.${DOMAIN?Variable not set}`)
        - traefik.http.routers.tracking-webservice-http.entrypoints=web
        - traefik.http.routers.tracking-webservice-http.middlewares=https-redirect
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.tracking-webservice-https.rule=Host(`tracking-api.${DOMAIN?Variable not set}`)
        - traefik.http.routers.tracking-webservice-https.entrypoints=websecure
        - traefik.http.routers.tracking-webservice-https.tls=true
        - traefik.http.routers.tracking-webservice-https.tls.certresolver=ljunggrenResolver
        - traefik.http.services.tracking-webservice.loadbalancer.server.port=8080
        - traefik.http.services.tracking-webservice.loadbalancer.server.scheme=http
    environment:
      - TZ=America/New_York

networks:
  traefik-public:
    external: true

configs:
  okta_ws_tomcat-users.xml:
    external: true
  tracking-webservice.properties:
    external: true
